package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	factschema "github.com/ncode/facts/internal/schema"
)

const schemaPath = factschema.DefaultPath

func main() {
	if code := runMain(os.Stderr); code != 0 {
		os.Exit(code)
	}
}

func runMain(stderr io.Writer) int {
	docs, err := renderDocs(schemaPath)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	for path, content := range docs {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintf(stderr, "create %s: %v\n", filepath.Dir(path), err)
			return 1
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fmt.Fprintf(stderr, "write %s: %v\n", path, err)
			return 1
		}
	}
	return 0
}

func renderDocs(schemaFile string) (map[string]string, error) {
	schema, err := factschema.LoadFile(schemaFile)
	if err != nil {
		return nil, err
	}
	docs := map[string]string{
		"docs/supported-facts/README.md": renderIndex(schema),
	}
	for _, p := range factschema.Platforms() {
		doc, err := renderPlatform(schema, p)
		if err != nil {
			return nil, err
		}
		docs["docs/supported-facts/"+p.ID+".md"] = doc
	}
	return docs, nil
}

func renderIndex(schema factschema.Schema) string {
	var b strings.Builder
	writeHeader(&b, "Supported Facts")
	b.WriteString("These pages are generated from [`docs/schema/facts.yaml`](../schema/facts.yaml). ")
	b.WriteString("The examples are synthetic, platform-shaped output for documentation; the tables are the supported fact contract.\n\n")
	b.WriteString("| Platform | Supported facts |\n| --- | ---: |\n")
	for _, p := range factschema.Platforms() {
		fmt.Fprintf(&b, "| [%s](%s.md) | %d |\n", p.Label, p.ID, len(schema.EntriesForPlatform(p.ID)))
	}
	return b.String()
}

func renderPlatform(schema factschema.Schema, p factschema.Platform) (string, error) {
	entries := schema.EntriesForPlatform(p.ID)
	example, err := exampleOutput(p.ID)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	writeHeader(&b, p.Label+" Supported Facts")
	fmt.Fprintf(&b, "Generated from [`docs/schema/facts.yaml`](../schema/facts.yaml). `%s` entries may be absent on a host when their preconditions do not hold.\n\n", "conditional")
	fmt.Fprintf(&b, "## Example Output\n\n```console\n$ facts --json\n%s\n```\n\n", example)
	fmt.Fprintf(&b, "## Fact Contract\n\n%d schema entries include `%s`.\n\n", len(entries), p.ID)
	b.WriteString("| Fact | Type | Conditional | Description |\n| --- | --- | --- | --- |\n")
	for _, item := range entries {
		conditional := "no"
		if item.Entry.Conditional {
			conditional = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
			item.Path,
			item.Entry.Type,
			conditional,
			escapeMarkdown(item.Entry.Description),
		)
	}
	return b.String(), nil
}

func writeHeader(b *strings.Builder, title string) {
	fmt.Fprintf(b, "<!-- Code generated by `go run ./tools/supportedfacts`; DO NOT EDIT. -->\n\n# %s\n\n", title)
}

func escapeMarkdown(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	return strings.ReplaceAll(s, "|", `\|`)
}

func exampleOutput(platform string) (string, error) {
	raw, ok := exampleJSON[platform]
	if !ok {
		return "", fmt.Errorf("missing example JSON for platform %q", platform)
	}
	var out bytes.Buffer
	if err := json.Indent(&out, []byte(raw), "", "  "); err != nil {
		return "", fmt.Errorf("indent example JSON for platform %q: %w", platform, err)
	}
	return out.String(), nil
}

var exampleJSON = map[string]string{
	"linux": `{
		"disks": {"sda": {"serial_number": "S250NXAG959927J", "size": "64.00 GiB", "size_bytes": 68719476736, "type": "ssd"}},
		"filesystems": ["ext4", "tmpfs", "xfs"],
		"kernel": {"name": "Linux", "release": {"full": "6.8.0-31-generic", "major": "6", "minor": "8", "patch": "0"}, "version": {"full": "6.8.0"}},
		"networking": {"hostname": "linux01", "interfaces": {"eth0": {"ip": "192.0.2.10", "mac": "52:54:00:12:34:56", "mtu": 1500}}},
		"os": {"family": "Debian", "name": "Ubuntu", "release": {"major": "24", "full": "24.04"}},
		"partitions": {"/dev/sda1": {"filesystem": "ext4", "mount": "/", "size": "63.00 GiB", "size_bytes": 67645734912}},
		"path": ["/usr/local/bin", "/usr/bin", "/bin"]
	}`,
	"darwin": `{
		"filesystems": ["apfs", "autofs", "devfs"],
		"kernel": {"name": "Darwin", "release": {"full": "24.5.0", "major": "24", "minor": "5", "patch": "0"}, "version": {"full": "24.5.0"}},
		"networking": {"hostname": "macbook", "interfaces": {"en0": {"ip": "192.0.2.20", "mac": "3c:22:fb:00:00:01", "mtu": 1500}}},
		"os": {"family": "Darwin", "macosx": {"product": "macOS", "version": {"full": "15.5", "major": "15", "minor": "5"}}, "name": "Darwin"},
		"path": ["/usr/local/bin", "/usr/bin", "/bin"],
		"system_profiler": {"hardware": {"model_name": "MacBook Pro"}}
	}`,
	"windows": `{
		"fips_enabled": false,
		"kernel": {"name": "windows", "release": {"full": "10.0.22631", "major": "10", "minor": "0", "patch": "22631"}, "version": {"full": "10.0.22631"}},
		"networking": {"hostname": "winbuild01", "interfaces": {"Ethernet": {"ip": "192.0.2.30", "mac": "00:15:5d:00:00:01", "mtu": 1500}}},
		"os": {"family": "windows", "name": "windows", "windows": {"system32": "C:\\Windows\\System32"}},
		"path": ["C:\\Windows\\system32", "C:\\Windows"]
	}`,
	"freebsd": `{
		"disks": {"ada0": {"model": "Virtual Disk", "serial_number": "S250NXAG959927J", "size": "64.00 GiB", "size_bytes": 68719476736}},
		"kernel": {"name": "FreeBSD", "release": {"full": "14.3-RELEASE", "major": "14", "minor": "3"}, "version": {"full": "14.3"}},
		"networking": {"hostname": "freebsd01", "interfaces": {"vtnet0": {"ip": "192.0.2.40", "mac": "58:9c:fc:00:00:01", "mtu": 1500}}},
		"os": {"family": "FreeBSD", "name": "FreeBSD", "release": {"major": "14", "full": "14.3-RELEASE"}},
		"partitions": {"ada0p1": {"partlabel": "gptboot0", "size": "512.00 KiB", "size_bytes": 524288}},
		"path": ["/sbin", "/bin", "/usr/sbin", "/usr/bin"]
	}`,
	"openbsd": `{
		"disks": {"sd0": {"size": "10.00 GiB", "size_bytes": 10737418240}},
		"kernel": {"name": "OpenBSD", "release": {"full": "7.9", "major": "7", "minor": "9"}, "version": {"full": "7.9"}},
		"networking": {"hostname": "openbsd01", "interfaces": {"vio0": {"ip": "192.0.2.50", "mac": "52:54:00:12:34:79", "mtu": 1500}}},
		"os": {"family": "OpenBSD", "name": "OpenBSD", "release": {"major": "7", "minor": "9", "full": "7.9"}},
		"partitions": {"/dev/sd0a": {"filesystem": "4.2BSD", "mount": "/", "size": "1.15 GiB", "size_bytes": 1233534976}},
		"path": ["/sbin", "/bin", "/usr/sbin", "/usr/bin"]
	}`,
	"netbsd": `{
		"disks": {"ld4": {"size": "10.00 GiB", "size_bytes": 10737418240}},
		"kernel": {"name": "NetBSD", "release": {"full": "10.1", "major": "10", "minor": "1"}, "version": {"full": "10.1"}},
		"networking": {"hostname": "netbsd01", "interfaces": {"vioif0": {"ip": "192.0.2.60", "mac": "52:54:00:12:34:23", "mtu": 1500}}},
		"os": {"family": "NetBSD", "name": "NetBSD", "release": {"major": "10", "minor": "1", "full": "10.1"}},
		"partitions": {"/dev/dk1": {"filesystem": "ffs", "mount": "/", "partlabel": "netbsd-root", "size": "9.90 GiB", "size_bytes": 10632560640}},
		"path": ["/sbin", "/bin", "/usr/sbin", "/usr/bin"],
		"zfs": {"feature_numbers": ["1", "2", "3", "4", "5"], "version": "5"},
		"zpool": {"feature_numbers": ["1", "2", "3", "4", "5"], "version": "5000"}
	}`,
	"dragonfly": `{
		"kernel": {"name": "DragonFly", "release": {"full": "6.4-RELEASE", "major": "6", "minor": "4-RELEASE"}, "version": {"full": "6.4"}},
		"load_averages": {"1m": 0.00, "5m": 0.00, "15m": 0.00},
		"memory": {"system": {"total": "1.97 GiB", "total_bytes": 2110259200}, "swap": {"total": "2.00 GiB", "total_bytes": 2147483648}},
		"mountpoints": {"/": {"device": "da0s1d", "filesystem": "hammer2", "size": "118.22 GiB", "size_bytes": 126933073920}},
		"networking": {"hostname": "dragonfly01", "interfaces": {}},
		"os": {"family": "DragonFly", "name": "DragonFly", "release": {"major": "6", "minor": "4-RELEASE", "full": "6.4-RELEASE"}},
		"path": ["/sbin", "/usr/sbin", "/bin", "/usr/bin"]
	}`,
	"illumos": `{
		"kernel": {"name": "SunOS", "release": {"full": "5.11", "major": "5"}, "version": {"full": "5"}},
		"load_averages": {"1m": 0.01, "5m": 0.00, "15m": 0.00},
		"memory": {"system": {"total": "3.99 GiB", "total_bytes": 4286013440}, "swap": {"total": "2.49 GiB", "total_bytes": 2676846592}},
		"mountpoints": {"/": {"device": "rpool/ROOT/omnios-r151058", "size": "28.58 GiB", "size_bytes": 30685528064}},
		"networking": {"hostname": "omnios01", "interfaces": {"net0": {"ip": "192.0.2.70", "mac": "52:54:00:12:34:70", "mtu": 1500}}},
		"os": {"family": "illumos", "name": "OmniOS", "release": {"major": "151058", "full": "r151058"}},
		"path": ["/usr/bin", "/usr/sbin", "/sbin"],
		"zfs": {"feature_numbers": ["1", "2", "3", "4", "5"], "version": "5"},
		"zpool": {"feature_numbers": ["1", "2", "3", "4", "5"], "version": "5000"}
	}`,
	"plan9": `{
		"facterversion": "dev",
		"kernel": {"name": "Plan 9"},
		"memory": {"system": {"total": "1018.38 MiB", "total_bytes": 1067843584}},
			"networking": {"hostname": "plan9host", "interfaces": {"ether0": {"bindings": [{"address": "192.0.2.90", "netmask": "255.255.255.0", "network": "192.0.2.0"}], "ip": "192.0.2.90", "netmask": "255.255.255.0", "network": "192.0.2.0", "mac": "52:54:00:12:34:90"}}, "primary": "ether0", "ip": "192.0.2.90", "netmask": "255.255.255.0", "network": "192.0.2.0", "mac": "52:54:00:12:34:90"},
		"os": {"architecture": "amd64", "family": "Plan 9", "hardware": "amd64", "name": "Plan 9"},
		"path": ["/bin", "/usr/glenda/bin"],
		"processors": {"count": 1, "isa": "amd64", "models": ["Core 2/Xeon 3600"]},
		"system_uptime": {"days": 0, "hours": 23, "seconds": 83717, "uptime": "23:15 hours"},
		"timezone": "CET"
	}`,
}
